//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDateTime
    {
        public tblDateTime()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
    
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
        public virtual tblAppointment tblAppointment { get; set; }
    }
}
